import { Player } from "@remotion/player";
import type { NextPage } from "next";
import Head from "next/head";
import { useEffect, useState } from "react";
import { MyComposition } from "../remotion/MyComp/Composition";
import { defaultMyCompProps } from "../types/MyComp";

const Home: NextPage = () => {
  const [props, setProps] = useState(defaultMyCompProps);
  const [text, setText] = useState(JSON.stringify(props, null, 2));

  useEffect(() => {
    setProps(JSON.parse(text));
  }, [text]);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="p-10">
      <textarea
        name="props"
        id=""
        className="h-96 w-full bg-gray-300"
        value={text}
        onChange={(e) => setText(e.currentTarget.value)}
      />
      <Player
        component={MyComposition}
        inputProps={props}
        durationInFrames={120}
        fps={30}
        compositionHeight={1080}
        compositionWidth={1920}
        style={{ width: "100%" }}
        controls
        autoPlay
        loop
      />
      </div>
      
    </div>
  );
};

export default Home;
